### ISSUE TITLE
non-existent parameter "container.build_id"

### ISSUE THREAD

**Issue by videni** [rollerworks/PasswordStrengthBundle#98]
hi,  the `matthiasnoback/symfony-service-definition-validator` will cause [non-existent parameter "container.build_id"](https://github.com/symfony/symfony/issues/25695#issuecomment-355542799), any fix please?  I also created an issue [overblog/GraphQLBundle](https://github.com/overblog/GraphQLBundle/issues/588), it seems the `matthiasnoback/symfony-service-definition-validator` is not compatable with `overblog/GraphQLBundle`.

```
Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "container.build_id". in /Users/john/www/acme-application/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:100
Stack trace:
#0 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ParameterBag/EnvPlaceholderParameterBag.php(67): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('container.build...')
#1 /Users/john/www/acme-application/vendor/symfony/dependency-injection/Container.php(112): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('container.build...')
#2 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1268): Symfony\Component\DependencyInjection\Container->getParameter('container.build...')
#3 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1212): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(Symfony\Component\DependencyInjection\Parameter), Array, false)
#4 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1114): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, false)
#5 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(610): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, false, 'cache.validator')
#6 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1264): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('cache.validator', 1, Array, false)
#7 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1212): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(Symfony\Component\DependencyInjection\Reference), Array, false)
#8 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1114): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, false)
#9 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(610): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, false, '.1_PhpArrayAdap...')
#10 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1264): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('.1_PhpArrayAdap...', 1, Array, false)
#11 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1212): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(Symfony\Component\DependencyInjection\Reference), Array, false)
#12 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1114): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, false)
#13 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(610): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, false, 'validator.mappi...')
#14 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1264): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('validator.mappi...', 1, Array, false)
#15 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1212): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(Symfony\Component\DependencyInjection\Reference), Array, false)
#16 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1628): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array)
#17 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1166): Symfony\Component\DependencyInjection\ContainerBuilder->callMethod(Object(Symfony\Component\Validator\ValidatorBuilder), Array, Array)
#18 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(610): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, false, 'validator.build...')
#19 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1264): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('validator.build...', 1, Array, false)
#20 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1118): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(Symfony\Component\DependencyInjection\Reference), Array, false)
#21 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(610): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, false, 'debug.validator...')
#22 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1264): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('debug.validator...', 1, Array, false)
#23 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1212): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(Symfony\Component\DependencyInjection\Reference), Array, false)
#24 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1114): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, false)
#25 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(610): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, false, 'debug.validator')
#26 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1264): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('debug.validator', 3, Array, false)
#27 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1212): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(Symfony\Component\DependencyInjection\Reference), Array, false)
#28 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1114): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, false)
#29 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(610): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, false, 'Overblog\\GraphQ...')
#30 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1264): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('Overblog\\GraphQ...', 1, Array, false)
#31 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1212): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(Symfony\Component\DependencyInjection\TypedReference), Array, false)
#32 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1114): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array, false)
#33 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(610): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, false, 'Overblog\\GraphQ...')
#34 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1264): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('Overblog\\GraphQ...', 1, Array, false)
#35 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1212): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(Symfony\Component\DependencyInjection\Reference), Array, false)
#36 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1628): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array)
#37 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1166): Symfony\Component\DependencyInjection\ContainerBuilder->callMethod(Object(Overblog\GraphQLBundle\ExpressionLanguage\ExpressionLanguage), Array, Array)
#38 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(610): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, false, 'Overblog\\GraphQ...')
#39 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1264): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('Overblog\\GraphQ...', 1, Array, false)
#40 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1212): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Object(Symfony\Component\DependencyInjection\Reference), Array, false)
#41 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1628): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices(Array, Array)
#42 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(1166): Symfony\Component\DependencyInjection\ContainerBuilder->callMethod(Object(Overblog\GraphQLBundle\Generator\TypeGenerator), Array, Array)
#43 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(610): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, true, 'Overblog\\GraphQ...')
#44 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(588): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('Overblog\\GraphQ...', 1, Array, true)
#45 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(556): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('overblog_graphq...', 1)
#46 /Users/john/www/acme-application/vendor/overblog/graphql-bundle/src/DependencyInjection/Compiler/TypeGeneratorPass.php(17): Symfony\Component\DependencyInjection\ContainerBuilder->get('overblog_graphq...')
#47 /Users/john/www/acme-application/vendor/symfony/dependency-injection/Compiler/Compiler.php(94): Overblog\GraphQLBundle\DependencyInjection\Compiler\TypeGeneratorPass->process(Object(Oro\Component\DependencyInjection\ExtendedContainerBuilder))
#48 /Users/john/www/acme-application/vendor/symfony/dependency-injection/ContainerBuilder.php(754): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Oro\Component\DependencyInjection\ExtendedContainerBuilder))
#49 /Users/john/www/acme-application/vendor/symfony/http-kernel/Kernel.php(556): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#50 /Users/john/www/acme-application/vendor/symfony/http-kernel/Kernel.php(133): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#51 /Users/john/www/acme-application/vendor/lchrusciel/api-test-case/src/ApiTestCase.php(80): Symfony\Component\HttpKernel\Kernel->boot()
#52 phar:///usr/local/Cellar/phpunit/7.3.1/bin/phpunit/phpunit/Framework/TestSuite.php(703): ApiTestCase\ApiTestCase::createSharedKernel()
#53 phar:///usr/local/Cellar/phpunit/7.3.1/bin/phpunit/phpunit/Framework/TestSuite.php(750): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#54 phar:///usr/local/Cellar/phpunit/7.3.1/bin/phpunit/phpunit/TextUI/TestRunner.php(587): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#55 phar:///usr/local/Cellar/phpunit/7.3.1/bin/phpunit/phpunit/TextUI/Command.php(203): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#56 phar:///usr/local/Cellar/phpunit/7.3.1/bin/phpunit/phpunit/TextUI/Command.php(159): PHPUnit\TextUI\Command->run(Array, true)
#57 /usr/local/Cellar/phpunit/7.3.1/bin/phpunit(595): PHPUnit\TextUI\Command::main()
#58 {main}
```

**Comment by videni** [comment]
I installed this bundle with  `overblog/GraphQLBundle`,  they  are both enabled which are not conflict.

**Comment by sstok** [comment]
This is unrelated to this bundle, please use the Symfony provided support channels.
